bcgov/developer.connect

- web/site/app.vue
- web/site/components/Sbc/ProductCard.vue
- web/site/locales/en-CA.ts
- web/site/locales/fr-CA.ts
- web/site/pages/products/index.vue
issue: #43 
- create initial products/index page with product card components and data from card.yml files
(card dark mode background colour needs some thought)
> 43 product cards

- web/site/content/en-CA/products/bn/card.yml
- web/site/content/en-CA/products/br/card.yml
- web/site/content/en-CA/products/mhr/card.yml
- web/site/content/en-CA/products/pay/card.yml
- web/site/content/en-CA/products/ppr/card.yml
- web/site/content/en-CA/products/rs/card.yml
update the product card contents
> feat: update card contents

- web/site/.env.sample
- web/site/devops/vaults.env
- add firebase keys to vaults.env
- update env.example
Currently using business-ar for APP_ID, will need to update 1password then change this
> web: add firebase keys to vault env

- web/site/components/ButtonCodepen.vue
- web/site/components/content/ProseA.vue
- web/site/components/content/ProsePre.vue
- web/site/components/content/rs/BcrosSearchExample.vue
- web/site/content/en-CA/products/rs/web-component.md
- web/site/locales/en-CA.ts
- web/site/locales/fr-CA.ts
- web/site/nuxt.config.ts
- web/site/package.json
- web/site/pnpm-lock.yaml
- web/site/server/api/reg-search.ts
> Web component

- web/site/content/en-CA/products/br/overview.md
Issue #: /https://github.com/bcgov/entity/issues/22888
Description of changes:
Related PR:
Add business registry API postman collection #138
- Updated the download attribute in the Additional Resources section
> Update Business postman collection download attribute

- web/site/devops/vaults.env
- web/site/nuxt.config.ts
- web/site/package.json
- web/site/pnpm-lock.yaml
Issue: bcgov/entity#23603
Description:
Add the GTAG Module to support capturing Google Ananlytics.
- add GTAG Module
- add 1 Password vault for google-analytics
- add vault ENVVAR
- Use the GTAG ENVVAR - NUXT_PUBLIC_GTAG_ID=G-XXXXXXXXXX
> add GTag to manage Google Analytics

- web/site/nuxt.config.ts
> hard code gtag

- web/site/nuxt.config.ts
> Feature gtag envvar

- web/site/app/locales/en-CA.ts
- web/site/content/en-CA/products/1.get-started/1.account-setup.md
- web/site/content/en-CA/products/1.get-started/4.analytics-report.md
- web/site/content/en-CA/products/1.get-started/5.message-logging.md
- web/site/package.json
> Content Updates

- web/site/app/app.config.ts
- web/site/app/components/Sbc/Docs/AccordianNavigation.vue
- web/site/app/components/Sbc/Docs/NextPrevButton.vue
- web/site/app/components/Sbc/Docs/SideNavigation.vue
- web/site/app/components/content/ButtonDownloadSpec.vue
- web/site/app/layouts/docs.vue
- web/site/app/locales/en-CA.ts
- web/site/content/en-CA/products/br/card.yml
- web/site/content/en-CA/products/mhr/card.yml
- web/site/package.json
- updated designs for side navigation menu and docs page
- removed contents page navigation
> documents page design updates

- web/site/content/en-CA/products/ppr/card.yml
- web/site/package.json
*Issue #:* /bcgov/entity#25043
*Description of changes:*
- Add third bullet to PPR API card (amend, renew, discharge...).
> Update PPR API card content.

- .github/CODEOWNERS
- web/site/app/enums/product-names.ts
- web/site/app/tests/unit/utils/handleContentDirectoryLabel.test.ts
- web/site/content/en-CA/products/strr/card.yml
- web/site/content/en-CA/products/strr/overview.md
- web/site/public/strr/platform.yaml
Issue: bcgov/entity#25363
Adding the STRR spec and info to the developer's site.
> docs: short term rental registry (platform)

- web/site/public/br/business-spec.yaml
- web/site/public/mhr/mhr-spec.yaml
- web/site/public/pay/payment-spec.yaml
- web/site/public/ppr/ppr-spec.yaml
- web/site/public/rs/regsearch-spec.yaml
https://github.com/bcgov/entity/issues/25906
> add oas yamls

- web/site/public/ppr/ppr-spec.yaml
https://github.com/bcgov/entity/issues/25906
> fix registrationType description

- web/site/app/locales/en-CA.ts
- web/site/app/pages/products/index.vue
https://app.zenhub.com/workspaces/connect-6690070c1ee5ec09f20a0ec1/issues/gh/bcgov/entity/24998
> Updated page title for products page

- web/site/nuxt.config.ts
update path in nuxtconfig for all OAS yaml
> update all paths to base url

- web/site/app/components/Card/Navigation.vue
- web/site/app/error.vue
- web/site/app/locales/en-CA.ts
- web/site/app/pages/index.vue
- web/site/package.json
https://github.com/bcgov/entity/issues/26259
Add link to discourse forum and 404 page
> 26259 - Discourse link

- web/site/content/en-CA/products/pay/overview.md
> Add a note beside statement calls

- web/site/content/en-CA/products/br/overview.md
- web/site/public/br/business-spec.yaml
*Issue #:* /bcgov/entity#26882
Description of changes:
updating examples in API specs to sync the examples with the latest version
- IA
- Cont. in
- AR
- CoD
- Consent to Cont. out
- Voluntary dissolution
- Amalgamtion (Regular, Horizontal, Vertical)
- AGM Extension
- AGM Location change
- Alteration
> 26882 - update br api specs

- web/site/content/en-CA/products/1.get-started/2.apis-summary.md
- Added STRR to the list of published APIs
> add STRR to the APIs list

- web/site/content/en-CA/products/br/overview.md
*Issue #:* /bcgov/entity#27606
*Description of changes:*
remove FED filing from the sandbox limitations section
> 27606 - remove FED filing from sandbox limitations section

- web/site/content/en-CA/products/br/overview.md
- web/site/package.json
https://github.com/bcgov/entity/issues/25547
> update the fee link and package version 

- web/site/content/en-CA/products/br/overview.md
- web/site/package.json
https://github.com/bcgov/entity/issues/25547
> rollback the change in 25547
